version: "3.8"

services:
  postgresql:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
